"""Add notes to PR Model

Revision ID: 3d7ab41ae6e9
Revises: 792f62ac4a10
Create Date: 2025-01-02 14:49:02.698367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7ab41ae6e9'
down_revision: Union[str, None] = '792f62ac4a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
