"""test

Revision ID: 792f62ac4a10
Revises: 14bdc5672716
Create Date: 2024-12-30 13:14:04.202545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792f62ac4a10'
down_revision: Union[str, None] = '14bdc5672716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchase_request_raw_material_id_key', 'purchase_request', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('purchase_request_raw_material_id_key', 'purchase_request', ['raw_material_id'])
    # ### end Alembic commands ###
