"""update PO 'NEW' status, add supplier 'type' and' bank_account' 3

Revision ID: 80dc3bd18bc0
Revises: 906a85cf94d7
Create Date: 2025-01-23 21:37:11.365322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80dc3bd18bc0'
down_revision: Union[str, None] = '906a85cf94d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('type', sa.Enum('ONLINE', 'OFFLINE', name='suppliertype'), nullable=False, server_default='ONLINE'))
    op.add_column('supplier', sa.Column('bank_account', sa.String(length=255), nullable=True))
    op.execute("UPDATE supplier SET type = 'ONLINE' WHERE type IS NULL")
    op.execute("ALTER TYPE postatus ADD VALUE 'NEW';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'bank_account')
    op.drop_column('supplier', 'type')
    # ### end Alembic commands ###
