"""update PO db and PO relation 3

Revision ID: 906a85cf94d7
Revises: b6ef6a3e645f
Create Date: 2025-01-14 19:49:13.903753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906a85cf94d7'
down_revision: Union[str, None] = 'b6ef6a3e645f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('po_code', sa.String(length=255), nullable=False))
    op.add_column('purchase_order', sa.Column('raw_material_id', sa.Integer(), nullable=False))
    op.add_column('purchase_order', sa.Column('received_qty', sa.Float(), nullable=False))
    op.add_column('purchase_order', sa.Column('received_notes', sa.String(length=255), nullable=True))
    op.add_column('purchase_order', sa.Column('supplier_notes', sa.String(length=255), nullable=True))
    op.alter_column('purchase_order', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('purchase_order_purchase_request_id_key', 'purchase_order', type_='unique')
    op.create_foreign_key(None, 'purchase_order', 'raw_materials', ['raw_material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order', type_='foreignkey')
    op.create_unique_constraint('purchase_order_purchase_request_id_key', 'purchase_order', ['purchase_request_id'])
    op.alter_column('purchase_order', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('purchase_order', 'supplier_notes')
    op.drop_column('purchase_order', 'received_notes')
    op.drop_column('purchase_order', 'received_qty')
    op.drop_column('purchase_order', 'raw_material_id')
    op.drop_column('purchase_order', 'po_code')
    # ### end Alembic commands ###
