"""Add notes to PR Model #2

Revision ID: e121d6d82a28
Revises: 3d7ab41ae6e9
Create Date: 2025-01-02 15:00:47.582498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e121d6d82a28'
down_revision: Union[str, None] = '3d7ab41ae6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_request', sa.Column('notes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_request', 'notes')
    # ### end Alembic commands ###
